/*
 * Copyright (c) 2026 Rekluz Games. All rights reserved.
 */

package com.rekluzgames.nikakudorimahjong.presentation.quote

object QuoteProvider {

    private val quotes: Map<String, List<String>> = mapOf(

        "" to listOf(
            "Fall seven times, stand up eight.",
            "Even a dust heap yields a mountain.",
            "The bamboo that bends is stronger than the oak that resists.",
            "Beginnings are easy; continuing is hard.",
            "Wisdom and virtue are like the two wheels of a cart.",
            "One kind word can warm three winter months.",
            "The water that has flowed past will not turn the wheel again.",
            "A single arrow is easily broken, but not ten in a bundle.",
            "He who climbs the mountain must start at the bottom.",
            "Silence is a flower.",
            "Studying the old is the key to understanding the new.",
            "A journey of a thousand miles begins with a single step.",
            "The reverse side also has a reverse side.",
            "Vision without action is a daydream.",
            "The frog in the well knows nothing of the great ocean.",
            "Unless you enter the tiger's den, you cannot take the cubs.",
            "Ten men, ten colors.",
            "Experience the world and you will gain wisdom.",
            "Even a stone can become warm if sat on for three years.",
            "Gold is tested by fire; man by his words.",
            "Better to be the beak of a rooster than the tail of an ox.",
            "A bird does not foul its own nest.",
            "Don't give a gold coin to a cat.",
            "Waking up is the first step to progress.",
            "Persistence is the shortcut to success.",
            "The sun does not know who is right or wrong.",
            "If you do not enter the fire, you cannot find the gold.",
            "Every day is a good day.",
            "Be like the flower that gives its fragrance to the hand that crushes it.",
            "The willow does not break under the weight of the snow.",
            "Time flies like an arrow.",
            "It takes three years even to heat a stone.",
            "Dripping water pierces the stone.",
            "You don't feed a fish you've already caught.",
            "A kite does not give birth to a falcon.",
            "Start with politeness, end with politeness.",
            "Exhaust all human affairs and wait on heaven's decree."
        ),

        "ja" to listOf(
            "七転び八起き。",
            "塵も積もれば山となる。",
            "柔よく剛を制す。",
            "始めは易く、続けることは難し。",
            "知恵と徳は車の両輪のごとし。",
            "一言の親切は三冬を温める。",
            "流れた水は車輪を回さない。",
            "一本の矢は折れやすいが、十本の束は折れない。",
            "山に登る者は麓から始めなければならない。",
            "沈黙は花。",
            "温故知新。",
            "千里の道も一歩から。",
            "物事には裏の裏がある。",
            "行動なき夢は白昼夢に過ぎない。",
            "井の中の蛙、大海を知らず。",
            "虎穴に入らずんば虎子を得ず。",
            "十人十色。",
            "旅をすれば知恵がつく。",
            "石の上にも三年。",
            "金は火で試され、人は言葉で試される。",
            "鶏口となるも牛後となるなかれ。",
            "鳥は自分の巣を汚さない。",
            "猫に小判。",
            "目覚めることが進歩の第一歩。",
            "継続は力なり。",
            "太陽は善悪を問わない。",
            "火に入らなければ金は得られない。",
            "日日是好日。",
            "砕く手にも香りを与える花のようであれ。",
            "柳は雪の重さに折れない。",
            "光陰矢の如し。",
            "石も三年座れば温まる。",
            "雨垂れ石を穿つ。",
            "釣った魚に餌はやらない。",
            "鳶が鷹を生む。",
            "礼に始まり礼に終わる。",
            "人事を尽くして天命を待つ。"
        ),

        "ko" to listOf(
            "일곱 번 넘어져도 여덟 번 일어나라.",
            "티끌 모아 태산.",
            "휘는 대나무가 버티는 참나무보다 강하다.",
            "시작은 쉬워도 계속하기는 어렵다.",
            "지혜와 덕은 수레의 두 바퀴와 같다.",
            "따뜻한 말 한마디가 세 겨울을 녹인다.",
            "흘러간 물은 다시 수레를 돌리지 않는다.",
            "화살 하나는 쉽게 부러지지만 열 개는 부러지지 않는다.",
            "산을 오르려면 기슭에서 시작해야 한다.",
            "침묵은 꽃이다.",
            "옛것을 익히고 새것을 안다.",
            "천 리 길도 한 걸음부터.",
            "뒷면에도 뒷면이 있다.",
            "행동 없는 비전은 백일몽이다.",
            "우물 안 개구리는 넓은 바다를 모른다.",
            "호랑이 굴에 들어가야 호랑이 새끼를 잡는다.",
            "열 사람이면 열 가지 색깔.",
            "세상을 경험하면 지혜를 얻는다.",
            "돌 위에 앉아도 삼 년이면 따뜻해진다.",
            "금은 불로 시험되고, 사람은 말로 시험된다.",
            "닭의 머리가 될지언정 소의 꼬리는 되지 마라.",
            "새는 자기 둥지를 더럽히지 않는다.",
            "고양이에게 금화를 주지 마라.",
            "깨어나는 것이 발전의 첫걸음이다.",
            "끈기가 성공의 지름길이다.",
            "해는 누가 옳고 그른지 알지 못한다.",
            "불 속에 들어가지 않으면 금을 찾을 수 없다.",
            "날마다 좋은 날.",
            "자신을 짓밟는 손에도 향기를 주는 꽃처럼 되어라.",
            "버드나무는 눈의 무게에 부러지지 않는다.",
            "세월은 화살처럼 날아간다.",
            "돌도 삼 년이면 따뜻해진다.",
            "낙숫물이 댓돌을 뚫는다.",
            "잡은 고기에 미끼를 주지 않는다.",
            "솔개는 매를 낳지 않는다.",
            "예의로 시작하고 예의로 끝내라.",
            "인사를 다하고 하늘의 뜻을 기다려라."
        ),

        "fr" to listOf(
            "Tomber sept fois, se relever huit.",
            "Même un tas de poussière peut devenir une montagne.",
            "Le bambou qui plie est plus fort que le chêne qui résiste.",
            "Commencer est facile ; continuer est difficile.",
            "La sagesse et la vertu sont comme les deux roues d'un char.",
            "Un mot aimable peut réchauffer trois mois d'hiver.",
            "L'eau qui s'est écoulée ne fait plus tourner la roue.",
            "Une flèche se brise facilement, mais pas dix en faisceau.",
            "Celui qui gravit la montagne doit commencer par le bas.",
            "Le silence est une fleur.",
            "Étudier le passé pour comprendre le présent.",
            "Un voyage de mille lieues commence par un seul pas.",
            "L'envers a aussi son envers.",
            "Une vision sans action n'est qu'un rêve éveillé.",
            "La grenouille au fond du puits ne connaît pas le grand océan.",
            "On ne prend pas les lionceaux sans entrer dans l'antre.",
            "Dix hommes, dix couleurs.",
            "L'expérience du monde apporte la sagesse.",
            "Même une pierre s'échauffe après trois ans d'assise.",
            "L'or est éprouvé par le feu ; l'homme par ses paroles.",
            "Mieux vaut être la tête d'un coq que la queue d'un bœuf.",
            "L'oiseau ne souille pas son propre nid.",
            "Ne donne pas une pièce d'or à un chat.",
            "Se réveiller est le premier pas vers le progrès.",
            "La persévérance est le raccourci vers le succès.",
            "Le soleil ne sait pas qui a raison ou tort.",
            "Sans entrer dans le feu, on ne trouve pas l'or.",
            "Chaque jour est un bon jour.",
            "Sois comme la fleur qui offre son parfum à la main qui l'écrase.",
            "Le saule ne se brise pas sous le poids de la neige.",
            "Le temps fuit comme une flèche.",
            "Il faut trois ans pour réchauffer une pierre.",
            "L'eau qui goutte finit par percer la pierre.",
            "On ne nourrit pas un poisson déjà pêché.",
            "Le milan n'engendre pas le faucon.",
            "Commencer with politeness, terminar with politeness.",
            "Fais de ton mieux et laisse le ciel décider."
        ),

        "it" to listOf(
            "Cadere sette volte, rialzarsi otto.",
            "Anche un mucchio di polvere può diventare una montagna.",
            "Il bambù che si piega è più forte della quercia che resiste.",
            "Iniziare è facile; continuare è difficile.",
            "La saggezza e la virtù sono come le due ruote di un carro.",
            "Una parola gentile può scaldare tre mesi d'inverno.",
            "L'acqua che è già scorsa non fa più girare la ruota.",
            "Una freccia si spezza facilmente, ma non dieci insieme.",
            "Chi scala la montagna deve partire dalla base.",
            "Il silenzio è un fiore.",
            "Studiare il passato per comprendere il presente.",
            "Un viaggio di mille miglia inizia con un solo passo.",
            "Anche il rovescio ha il suo rovescio.",
            "Una visione senza azione è solo un sogno ad occhi aperti.",
            "La rana nel pozzo non conosce il grande oceano.",
            "Se non entri nella tana del tigre, non puoi prendere i cuccioli.",
            "Dieci persone, dieci colori.",
            "Vivere il mondo porta saggezza.",
            "Anche una pietra si scalda se ci si siede sopra per tre anni.",
            "L'oro si prova con il fuoco; l'uomo con le sue parole.",
            "Meglio essere il becco di un gallo che la coda di un bue.",
            "L'uccello non sporca il proprio nido.",
            "Non dare una moneta d'oro a un gatto.",
            "Svegliarsi è il primo passo verso il progresso.",
            "La perseveranza è la scorciatoia per il successo.",
            "Il sole non sa chi ha ragione o torto.",
            "Se non entri nel fuoco, non puoi trovare l'oro.",
            "Ogni giorno è un buon giorno.",
            "Sii come il fiore che offre il suo profumo alla mano che lo schiaccia.",
            "Il salice non si spezza sotto il peso della neve.",
            "Il tempo vola come una freccia.",
            "Ci vogliono tre anni per scaldare una pietra.",
            "L'acqua che gocciola perfora la pietra.",
            "Non si dà da mangiare a un pesce già pescato.",
            "Il nibbio non genera il falcone.",
            "Inizia con cortesia, finisci con cortesia.",
            "Fai del tuo meglio e attendi il volere del cielo."
        ),

        "es" to listOf(
            "Caer siete veces, levantarse ocho.",
            "Incluso un montón de polvo puede convertirse en una montaña.",
            "El bambú que se dobla es más fuerte que el roble que resiste.",
            "Empezar es fácil; continuar es difícil.",
            "La sabiduría y la virtud son como las dos ruedas de un carro.",
            "Una palabra amable puede calentar tres meses de invierno.",
            "El agua que ya ha pasado no vuelve a mover la rueda.",
            "Una flecha se rompe fácilmente, pero no diez juntas.",
            "Quien escala la montaña debe empezar desde abajo.",
            "El silencio es una flor.",
            "Estudiar lo antiguo es la clave para entender lo nuevo.",
            "Un viaje de mil millas comienza con un solo paso.",
            "El reverso también tiene su reverso.",
            "Una visión sin acción no es más que un sueño.",
            "La rana en el pozo no conoce el gran océano.",
            "Si no entras en la guarida del tigre, no puedes llevarte sus cachorros.",
            "Diez personas, diez colores.",
            "Experimentar el mundo te da sabiduría.",
            "Hasta una piedra se calienta si se sienta en ella tres años.",
            "El oro se prueba con fuego; el hombre con sus palabras.",
            "Mejor ser el pico del gallo que la cola del buey.",
            "El pájaro no ensucia su propio nido.",
            "No le des una moneda de oro a un gato.",
            "Despertar es el primer paso hacia el progreso.",
            "La perseverancia es el atajo hacia el éxito.",
            "El sol no sabe quién tiene razón o no.",
            "Si no entras en el fuego, no puedes encontrar el oro.",
            "Cada día es un buen día.",
            "Sé como la flor que da su fragancia a la mano que la aplasta.",
            "El sauce no se rompe bajo el peso de la nieve.",
            "El tiempo vuela como una flecha.",
            "Se necesitan tres años para calentar una piedra.",
            "El agua que gotea perfora la roca.",
            "No se alimenta al pez que ya fue pescado.",
            "El milano no engendra al halcón.",
            "Empieza con cortesía, termina con cortesía.",
            "Haz todo lo que puedas y espera el decreto del cielo."
        ),

        "tl" to listOf(
            "Mabuwal nang pitong beses, bumangon nang walo.",
            "Kahit alikabok, kung maipong-maipon, magiging bundok.",
            "Ang kawayan na yumuyuko ay mas matibay sa oak na lumalaban.",
            "Madaling magsimula; mahirap ituloy.",
            "Ang karunungan at kabutihan ay parang dalawang gulong ng kariton.",
            "Ang isang mabuting salita ay magpapainit ng tatlong buwan ng taglamig.",
            "Ang tubig na lumipas na ay hindi na magpapaikot ng gulong.",
            "Madaling mabasag ang isang palaso, ngunit hindi ang sampung magkakasama.",
            "Ang umakyat ng bundok ay dapat magsimula sa ibaba.",
            "Ang katahimikan ay isang bulaklak.",
            "Ang pag-aaral ng luma ay susi sa pag-unawa ng bago.",
            "Ang isang libong milyong paglalakbay ay nagsisimula sa isang hakbang.",
            "Ang kabilang mukha ay may sariling kabilang mukha.",
            "Ang pangarap na walang kilos ay isang panaginip lamang.",
            "Ang palaka sa balon ay walang alam sa malawak na karagatan.",
            "Kung hindi ka papasok sa yungib ng tigre, hindi mo matatanggap ang kanyang anak.",
            "Sampung tao, sampung kulay.",
            "Ang karanasan sa mundo ay nagbibigay ng karunungan.",
            "Kahit ang bato ay magiging mainit kung uupuan nang tatlong taon.",
            "Ang ginto ay sinusubok ng apoy; ang tao ay ng kanyang mga salita.",
            "Mas mabuting maging tuka ng manok kaysa buntot ng baka.",
            "Hindi dinudumihan ng ibon ang sarili nitong pugad.",
            "Huwag magbigay ng gintong barya sa pusa.",
            "Ang pagkagising ay ang unang hakbang patungo sa pag-unlad.",
            "Ang pagtitiyaga ay ang pinakamaikling landas sa tagumpay.",
            "Hindi alam ng araw kung sino ang tama o mali.",
            "Kung hindi ka papasok sa apoy, hindi mo mahahanap ang ginto.",
            "Bawat araw ay isang magandang araw.",
            "Maging tulad ng bulaklak na nagbibigay ng halimuyak sa kamay na sumusugpok sa kanya.",
            "Hindi nababasag ang puno ng willow sa bigat ng niyebe.",
            "Lumilipad ang panahon tulad ng palaso.",
            "Tatlong taon ang kailangan para mainit ang bato.",
            "Ang patibong na tubig ay tumatibag ng bato.",
            "Hindi mo na pinakakain ang isdang nahuli mo na.",
            "Ang salanggapang ay hindi nanganganak ng agila.",
            "Magsimula nang may kagandahang-loob, tapusin nang may kagandahang-loob.",
            "Gawin ang lahat ng makakaya at hintayin ang utos ng langit."
        )
    )

    fun getShuffledQuotes(language: String): MutableList<String> =
        (quotes[language] ?: quotes[""]!!).shuffled().toMutableList()
}
